export * from './lib/popular-news/popular-news'
export * from './lib/notfound-page/notfound-page'
export * from './lib/latest-news/latest-news'
export * from './lib/home/home'
export * from './lib/pages-web'
